version: "2.1"
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /share/CACHEDEV1_DATA/Container/nzbget:/config
      - /share/CACHEDEV1_DATA/Downloads/NZBGet:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /share/CACHEDEV1_DATA/Container/radarr:/config
      - /share/CACHEDEV1_DATA/Media:/movies #optional
      - /share/CACHEDEV1_DATA/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
    volumes:
      - /share/CACHEDEV1_DATA/Container/sonarr:/config
      - /share/CACHEDEV1_DATA/Media/TV:/tv
      - /share/CACHEDEV1_DATA/NZBGet/completed/TV:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - VERSION=docker
    volumes:
      - /share/CACHEDEV1_DATA/Container/plex:/config
      - /share/CACHEDEV1_DATA/Media/TV:/tv
      - /share/CACHEDEV1_DATA/Media/Movies:/movies
      - /share/CACHEDEV1_DATA/Media/Photos:/photos
      - /share/CACHEDEV1_DATA/Backups/plex_db:/db_backups
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/CACHEDEV1_DATA/Container/portainer:/data
    ports:
      - 9000:9000
      - 8000:8000
    restart: unless-stopped
